return {
	-- cmd = {
	-- 	"lua-language-server",
	-- },
	-- filetypes = {
	-- 	"lua",
	-- },
	-- root_markers = {
	-- 	".luarc.json",
	-- 	".luarc.jsonc",
	-- },

	-- settings = {
	-- 	Lua = {
	-- 		runtime = {
	-- 			-- LuaJIT in the case of Neovim
	-- 			version = "LuaJIT",
	-- 			path = vim.split(package.path, ";"),
	-- 		},
	-- 		diagnostics = {
	-- 			-- Get the language server to recognize the `vim` global
	-- 			globals = { "vim" },
	-- 		},
	-- 		workspace = {
	-- 			checkThirdParty = false,
	-- 			-- Make the server aware of Neovim runtime files
	-- 			library = {
	-- 				[vim.fn.expand("$VIMRUNTIME/lua")] = true,
	-- 				[vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
	-- 			},
	-- 		},
	-- 	},
	-- },
}
